/*
 * Name: VodFlowPlayer SewisePlayerSkin framework V1.0.0
 * Author: Jack Zhang
 * Website: http://www.sewise.com/
 * Date: 12th June 2014
 * Copyright: 2014, Sewise
 * 
 */

(function(b){b.SewisePlayerSkin={version:"1.0.0"};b.SewisePlayer=b.SewisePlayer||{}})(window);(function(b){b.SewisePlayer.IVodPlayer=b.SewisePlayer.IVodPlayer||{play:function(){},pause:function(){},stop:function(){},seek:function(){},changeClarity:function(){},setVolume:function(){},toPlay:function(){},duration:function(){},playTime:function(){},type:function(){},showTextTip:function(){},hideTextTip:function(){},muted:function(){}}})(window);(function(b){b.SewisePlayerSkin.IVodSkin=b.SewisePlayerSkin.IVodSkin||{player:function(){},started:function(){},paused:function(){},stopped:function(){},seeking:function(){},buffering:function(){},bufferProgress:function(){},loadedProgress:function(){},programTitle:function(){},duration:function(){},playTime:function(){},startTime:function(){},loadSpeed:function(){},initialClarity:function(){},lang:function(){},logo:function(){},timeUpdate:function(){},volume:function(){},clarityButton:function(){},
timeDisplay:function(){},controlBarDisplay:function(){},topBarDisplay:function(){},customStrings:function(){}}})(window);(function(){SewisePlayerSkin.Utils={stringer:{time2FigFill:function(b){var a,b=Math.floor(b);10>b?a="0"+b:a=""+b;return a},secondsToHMS:function(b){if(!(0>b)){var a=this.time2FigFill(Math.floor(b/3600)),d=this.time2FigFill(b/60%60),b=this.time2FigFill(b%60);return a+":"+d+":"+b}},secondsToMS:function(b){if(!(0>b)){var a=this.time2FigFill(b/60),b=this.time2FigFill(b%60);return a+":"+b}},dateToTimeString:function(b){var a;a=b?b:new Date;var b=a.getFullYear(),d=a.getMonth()+1,c=a.getDate(),m=this.time2FigFill(a.getHours()),
f=this.time2FigFill(a.getMinutes());a=this.time2FigFill(a.getSeconds());return b+"-"+d+"-"+c+" "+m+":"+f+":"+a},dateToTimeStr14:function(b){var a=b.getFullYear(),d=this.time2FigFill(b.getMonth()+1),c=this.time2FigFill(b.getDate()),m=this.time2FigFill(b.getHours()),f=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+d+c+m+f+b},dateToStrHMS:function(b){var a=this.time2FigFill(b.getHours()),d=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+
":"+d+":"+b}}}})();(function(b){SewisePlayerSkin.ElementObject=function(){this.$sewisePlayerUi=b(".sewise-player-ui");this.$container=this.$sewisePlayerUi.parent();this.$video=this.$container.find("video").get(0);this.$controlbar=this.$sewisePlayerUi.find(".controlbar");this.$playBtn=this.$sewisePlayerUi.find(".controlbar-btns-play");this.$pauseBtn=this.$sewisePlayerUi.find(".controlbar-btns-pause");this.$stopBtn=this.$sewisePlayerUi.find(".controlbar-btns-stop");this.$fullscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-fullscreen");
this.$normalscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-normalscreen");this.$soundopenBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundopen");this.$soundcloseBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundclose");this.$volumelineVolume=this.$sewisePlayerUi.find(".controlbar-volumeline-volume");this.$volumelineDragger=this.$sewisePlayerUi.find(".controlbar-volumeline-dragger");this.$volumelinePoint=this.$sewisePlayerUi.find(".controlbar-volumeline-point");this.$playtime=this.$sewisePlayerUi.find(".controlbar-playtime");
this.$totaltime=this.$sewisePlayerUi.find(".controlbar-totaltime");this.$controlBarProgress=this.$sewisePlayerUi.find(".controlbar-progress");this.$progressPlayedLine=this.$sewisePlayerUi.find(".controlbar-progress-playedline");this.$progressPlayedPoint=this.$sewisePlayerUi.find(".controlbar-progress-playpoint");this.$progressLoadedLine=this.$sewisePlayerUi.find(".controlbar-progress-loadedline");this.$progressSeekLine=this.$sewisePlayerUi.find(".controlbar-progress-seekline");this.$logo=this.$sewisePlayerUi.find(".logo");
this.$logoIcon=this.$sewisePlayerUi.find(".logo-icon");this.$topbar=this.$sewisePlayerUi.find(".topbar");this.$programTitle=this.$sewisePlayerUi.find(".topbar-program-title");this.$topbarClock=this.$sewisePlayerUi.find(".topbar-clock");this.$buffer=this.$sewisePlayerUi.find(".buffer");this.$bigPlayBtn=this.$sewisePlayerUi.find(".big-play-btn");this.defStageWidth=this.$container.width();this.defStageHeight=this.$container.height();this.defLeftValue=parseInt(this.$container.css("left"));this.defTopValue=
parseInt(this.$container.css("top"));this.defOffsetX=this.$container.get(0).getBoundingClientRect().left;this.defOffsetY=this.$container.get(0).getBoundingClientRect().top;this.defOverflow=b("body").css("overflow")}})(window.jQuery);(function(b){SewisePlayerSkin.ElementLayout=function(a){function d(){null!=document.fullscreenElement||null!=document.msFullscreenElement||null!=document.mozFullScreenElement||null!=document.webkitFullscreenElement?q.fullScreen():q.normalScreen()}var c=a.$container,m=a.$controlBarProgress,f=a.$playtime,q=this,h=a.defStageWidth,C=a.defStageHeight,D=a.defLeftValue,E=a.defTopValue,M=a.defOffsetX,w=a.defOffsetY,u=a.defOverflow,l=parseInt(h)-265;0>l&&(l+=f.width(),f.hide());m.css("width",l);document.addEventListener("fullscreenchange",
d);document.addEventListener("MSFullscreenChange",d);document.addEventListener("mozfullscreenchange",d);document.addEventListener("webkitfullscreenchange",d);this.fullScreen=function(a){if("not-support"==a){var a=b(window).width(),d=b(window).height()-8;c.css("width",a);c.css("height",d);a=E-w+"px";c.css("left",D-M+"px");c.css("top",a);b("body").css("overflow","hidden")}else c.css("width","100%"),c.css("height","100%");a=parseInt(c.width())-265;0>a?(a+=f.width(),f.hide()):f.show();m.css("width",a)};
this.normalScreen=function(){c.css("width",h);c.css("height",C);c.css("left",D);c.css("top",E);b("body").css("overflow",u);l=parseInt(h)-265;0>l?(l+=f.width(),f.hide()):f.show();m.css("width",l)}}})(window.jQuery);(function(){SewisePlayerSkin.LogoBox=function(b){var a=b.$logoIcon;this.setLogo=function(b){a.css("background","url("+b+") 0px 0px no-repeat");a.attr("href","http://www.sewise.com/")}}})(window.jQuery);(function(){SewisePlayerSkin.TopBar=function(b){var a=b.$topbar,d=b.$programTitle,c=b.$topbarClock;setInterval(function(){var a=SewisePlayerSkin.Utils.stringer.dateToTimeString();c.text(a)},1E3);this.setTitle=function(a){d.text(a)};this.show=function(){a.css("visibility","visible")};this.hide=function(){a.css("visibility","hidden")};this.hide2=function(){a.hide()}}})(window.jQuery);(function(b){SewisePlayerSkin.ControlBar=function(a,d,c){function m(a){a=j+(a.pageX-x);0<a&&a<r&&(s.css("width",a),n.css("left",a-F/2))}function f(a){u.unbind("mousemove",m);b(document).unbind("mouseup",f);P=a.pageX;x!=P&&(j=s.width(),y=j/r,i.seek(y*z));G=!1}function q(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=j+(e.targetTouches[0].pageX-x),0<a&&a<r&&(s.css("width",a),n.css("left",a-F/2)))}function h(a){e=a.originalEvent;n.unbind("touchmove",q);n.unbind("touchend",h);if(1==
e.changedTouches.length)P=e.changedTouches[0].pageX,x!=P&&(j=s.width(),y=j/r,i.seek(y*z));G=!1}function C(a){a=g+(a.pageX-A);0<a&&a<o&&(p.css("width",a),k.css("left",a-v/2))}function D(a){u.unbind("mousemove",C);b(document).unbind("mouseup",D);Q=a.pageX;A!=Q&&(g=p.width(),t=g/o,i.setVolume(t),w())}function E(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=g+(e.targetTouches[0].pageX-A),0<a&&a<o&&(p.css("width",a),k.css("left",a-v/2)))}function M(a){e=a.originalEvent;k.unbind("touchmove",
E);k.unbind("touchend",M);if(1==e.changedTouches.length)Q=e.changedTouches[0].pageX,A!=Q&&(g=p.width(),t=g/o,i.setVolume(t),w())}function w(){0<t?(i.muted(!1),H.show(),B.hide()):(i.muted(!0),H.hide(),B.show())}var u=a.$container,l=a.$video,N=a.$controlbar,O=a.$playBtn,I=a.$pauseBtn,X=a.$stopBtn,R=a.$fullscreenBtn,J=a.$normalscreenBtn,H=a.$soundopenBtn,B=a.$soundcloseBtn,p=a.$volumelineVolume,K=a.$volumelineDragger,k=a.$volumelinePoint,Y=a.$playtime,Z=a.$totaltime,s=a.$progressPlayedLine,n=a.$progressPlayedPoint,
$=a.$progressLoadedLine,L=a.$progressSeekLine,aa=a.$buffer,S=a.$bigPlayBtn,i,z=0.1,T=0,V="00:00:00",W="00:00:00",F=0,G=!1,x=0,P=0,j=0,r=0,y=0,U=!0,v=0,o=0,g=0,t=0,A=0,Q=0,F=n.width(),r=L.width(),v=k.width(),o=K.width();I.hide();J.hide();B.hide();aa.hide();N.click(function(a){a.originalEvent.stopPropagation()});u.click(function(){U?(N.css("visibility","hidden"),c.hide(),U=!1):(N.css("visibility","visible"),c.show(),U=!0)});O.click(function(){i.play()});I.click(function(){i.pause()});X.click(function(){i.stop()});
S.click(function(a){a.originalEvent.stopPropagation();i.play()});R.click(function(){R.hide();J.show();var a=u.get(0);a.requestFullscreen?a.requestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():l.webkitEnterFullscreen?(l.play(),l.webkitEnterFullscreen(),R.show(),J.hide()):d.fullScreen("not-support")});J.click(function(){R.show();J.hide();document.exitFullscreen?document.exitFullscreen():
document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():d.normalScreen()});H.click(function(){i.muted(!0);H.hide();B.show();p.css("width",0);k.css("left",-v/2)});B.click(function(){i.muted(!1);H.show();B.hide();p.css("width",g);k.css("left",g-v/2)});L.mousedown(function(a){j=a.pageX-a.target.getBoundingClientRect().left;r=L.width();s.css("width",j);n.css("left",j-F/2);y=j/r;
i.seek(y*z)});n.mousedown(function(a){this.blur();G=!0;x=a.pageX;j=s.width();r=L.width();u.bind("mousemove",m);b(document).bind("mouseup",f)});n.bind("touchstart",function(a){e=a.originalEvent;n.blur();a=e.targetTouches[0];G=!0;x=a.pageX;j=s.width();r=L.width();n.bind("touchmove",q);n.bind("touchend",h)});K.mousedown(function(a){g=a.pageX-a.target.getBoundingClientRect().left;o=K.width();p.css("width",g);k.css("left",g-v/2);t=g/o;i.setVolume(t);w()});k.mousedown(function(a){this.blur();A=a.pageX;
g=p.width();o=K.width();u.bind("mousemove",C);b(document).bind("mouseup",D)});k.bind("touchstart",function(a){e=a.originalEvent;k.blur();A=e.targetTouches[0].pageX;g=p.width();o=K.width();k.bind("touchmove",E);k.bind("touchend",M)});this.setPlayer=function(a){i=a};this.started=function(){O.hide();I.show();S.hide()};this.paused=function(){O.show();I.hide();S.show()};this.stopped=function(){O.show();I.hide();S.show()};this.setDuration=function(a){z=a;W=SewisePlayerSkin.Utils.stringer.secondsToMS(z);
Z.text(W)};this.timeUpdate=function(a){T=a;V=SewisePlayerSkin.Utils.stringer.secondsToMS(T);Y.text(V);G||(j=100*(T/z)+"%",s.css("width",j),a=s.width()-F/2,n.css("left",a))};this.loadProgress=function(a){$.css("width",100*a+"%")};this.initVolume=function(a){t=a;g=o*t;p.css("width",g);k.css("left",g-v/2);w()};this.hide2=function(){N.hide()}}})(window.jQuery);(function(b,a){a(document).ready(function(){var a=SewisePlayer.IVodPlayer,b=new SewisePlayerSkin.ElementObject,m=new SewisePlayerSkin.ElementLayout(b),f=new SewisePlayerSkin.LogoBox(b),q=new SewisePlayerSkin.TopBar(b),h=new SewisePlayerSkin.ControlBar(b,m,q);SewisePlayerSkin.IVodSkin.player=function(b){a=b;h.setPlayer(a)};SewisePlayerSkin.IVodSkin.started=function(){h.started()};SewisePlayerSkin.IVodSkin.paused=function(){h.paused()};SewisePlayerSkin.IVodSkin.stopped=function(){h.stopped()};SewisePlayerSkin.IVodSkin.duration=
function(a){h.setDuration(a)};SewisePlayerSkin.IVodSkin.timeUpdate=function(a){h.timeUpdate(a)};SewisePlayerSkin.IVodSkin.loadedProgress=function(a){h.loadProgress(a)};SewisePlayerSkin.IVodSkin.programTitle=function(a){q.setTitle(a)};SewisePlayerSkin.IVodSkin.logo=function(a){f.setLogo(a)};SewisePlayerSkin.IVodSkin.volume=function(a){h.initVolume(a)};SewisePlayerSkin.IVodSkin.initialClarity=function(){};SewisePlayerSkin.IVodSkin.clarityButton=function(){};SewisePlayerSkin.IVodSkin.timeDisplay=function(){};
SewisePlayerSkin.IVodSkin.controlBarDisplay=function(a){"enable"!=a&&h.hide2()};SewisePlayerSkin.IVodSkin.topBarDisplay=function(a){"enable"!=a&&q.hide2()};SewisePlayerSkin.IVodSkin.customStrings=function(){};try{SewisePlayer.CommandDispatcher.dispatchEvent({type:SewisePlayer.Events.PLAYER_SKIN_LOADED,playerSkin:SewisePlayerSkin.IVodSkin})}catch(C){console.log("No Main Player")}})})(window,window.jQuery);
