/*
 * Name: VodFlowPlayer SewisePlayerSkin framework V1.0.0
 * Author: Jack Zhang
 * Website: http://www.sewise.com/
 * Date: 12th June 2014
 * Copyright: 2014, Sewise
 * 
 */


(function(b){b.SewisePlayerSkin={version:"1.0.0"};b.SewisePlayer=b.SewisePlayer||{}})(window);(function(b){b.SewisePlayer.IVodPlayer=b.SewisePlayer.IVodPlayer||{play:function(){},pause:function(){},stop:function(){},seek:function(){},changeClarity:function(){},setVolume:function(){},toPlay:function(){},duration:function(){},playTime:function(){},type:function(){},showTextTip:function(){},hideTextTip:function(){},muted:function(){}}})(window);(function(b){b.SewisePlayerSkin.IVodSkin=b.SewisePlayerSkin.IVodSkin||{player:function(){},started:function(){},paused:function(){},stopped:function(){},seeking:function(){},buffering:function(){},bufferProgress:function(){},loadedProgress:function(){},programTitle:function(){},duration:function(){},playTime:function(){},startTime:function(){},loadSpeed:function(){},initialClarity:function(){},lang:function(){},logo:function(){},clarityButton:function(){},timeDisplay:function(){},controlBarDisplay:function(){},
topBarDisplay:function(){},timeUpdate:function(){},volume:function(){}}})(window);(function(){SewisePlayerSkin.Utils={stringer:{secondsToHMS:function(b){if(!(0>b)){var c=this.time2FigFill(Math.floor(b/3600)),m=this.time2FigFill(b/60%60),b=this.time2FigFill(b%60);return c+":"+m+":"+b}},secondsToMS:function(b){if(!(0>b)){var c=this.time2FigFill(b/60),b=this.time2FigFill(b%60);return c+":"+b}},time2FigFill:function(b){var c,b=Math.floor(b);10>b?c="0"+b:c=""+b;return c},dateToTimeString:function(){var b=new Date,c=b.getFullYear(),m=b.getMonth()+1,i=b.getDate(),o=this.time2FigFill(b.getHours()),
f=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return c+"-"+m+"-"+i+" "+o+":"+f+":"+b}}}})();(function(b){SewisePlayerSkin.ElementObject=function(){this.$sewisePlayerUi=b(".sewise-player-ui");this.$container=this.$sewisePlayerUi.parent();this.$video=this.$container.find("video").get(0);this.$controlbar=this.$sewisePlayerUi.find(".controlbar");this.$playBtn=this.$sewisePlayerUi.find(".controlbar-btns-play");this.$pauseBtn=this.$sewisePlayerUi.find(".controlbar-btns-pause");this.$stopBtn=this.$sewisePlayerUi.find(".controlbar-btns-stop");this.$fullscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-fullscreen");
this.$normalscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-normalscreen");this.$soundopenBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundopen");this.$soundcloseBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundclose");this.$volumelineVolume=this.$sewisePlayerUi.find(".controlbar-volumeline-volume");this.$volumelineDragger=this.$sewisePlayerUi.find(".controlbar-volumeline-dragger");this.$volumelinePoint=this.$sewisePlayerUi.find(".controlbar-volumeline-point");this.$playtime=this.$sewisePlayerUi.find(".controlbar-playtime");
this.$totaltime=this.$sewisePlayerUi.find(".controlbar-totaltime");this.$controlBarProgress=this.$sewisePlayerUi.find(".controlbar-progress");this.$progressPlayedLine=this.$sewisePlayerUi.find(".controlbar-progress-playedline");this.$progressPlayedPoint=this.$sewisePlayerUi.find(".controlbar-progress-playpoint");this.$progressLoadedLine=this.$sewisePlayerUi.find(".controlbar-progress-loadedline");this.$progressSeekLine=this.$sewisePlayerUi.find(".controlbar-progress-seekline");this.$logo=this.$sewisePlayerUi.find(".logo");
this.$logoIcon=this.$sewisePlayerUi.find(".logo-icon");this.$topbar=this.$sewisePlayerUi.find(".topbar");this.$programTitle=this.$sewisePlayerUi.find(".topbar-program-title");this.$topbarClock=this.$sewisePlayerUi.find(".topbar-clock");this.$buffer=this.$sewisePlayerUi.find(".buffer");this.$bigPlayBtn=this.$sewisePlayerUi.find(".big-play-btn");this.defStageWidth=this.$container.width();this.defStageHeight=this.$container.height()}})(window.jQuery);(function(b){SewisePlayerSkin.ElementLayout=function(c){function m(){null!=document.fullscreenElement||null!=document.msFullscreenElement||null!=document.mozFullScreenElement||null!=document.webkitFullscreenElement?u.fullScreen():u.normalScreen()}var i=c.$container,o=c.$controlBarProgress,f=c.$playtime,u=this,g=c.defStageWidth,C=c.defStageHeight,j=parseInt(g)-265;0>j&&(j+=f.width(),f.hide());o.css("width",j);document.addEventListener("fullscreenchange",m);document.addEventListener("MSFullscreenChange",
m);document.addEventListener("mozfullscreenchange",m);document.addEventListener("webkitfullscreenchange",m);this.fullScreen=function(c){if("not-support"==c){var c=b(window).width(),j=b(window).height();i.css("width",c);i.css("height",j)}else i.css("width","100%"),i.css("height","100%");c=parseInt(i.width())-265;0>c?(c+=f.width(),f.hide()):f.show();o.css("width",c)};this.normalScreen=function(){i.css("width",g);i.css("height",C);j=parseInt(g)-265;0>j?(j+=f.width(),f.hide()):f.show();o.css("width",
j)}}})(window.jQuery);(function(){SewisePlayerSkin.LogoBox=function(b){var c=b.$logoIcon;this.setLogo=function(b){c.css("background","url("+b+") 0px 0px no-repeat");c.attr("href","http://www.sewise.com/")}}})(window.jQuery);(function(){SewisePlayerSkin.TopBar=function(b){var c=b.$topbar,m=b.$programTitle,i=b.$topbarClock;setInterval(function(){var b=SewisePlayerSkin.Utils.stringer.dateToTimeString();i.text(b)},1E3);this.setTitle=function(b){m.text(b)};this.show=function(){c.css("visibility","visible")};this.hide=function(){c.css("visibility","hidden")}}})(window.jQuery);(function(b){SewisePlayerSkin.ControlBar=function(c,m,i){function o(a){a=k+(a.pageX-w);0<a&&a<r&&(s.css("width",a),n.css("left",a-D/2))}function f(a){x.unbind("mousemove",o);b(document).unbind("mouseup",f);K=a.pageX;w!=K&&(k=s.width(),y=k/r,h.seek(y*z));E=!1}function u(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=k+(e.targetTouches[0].pageX-w),0<a&&a<r&&(s.css("width",a),n.css("left",a-D/2)))}function g(a){e=a.originalEvent;n.unbind("touchmove",u);n.unbind("touchend",g);if(1==
e.changedTouches.length)K=e.changedTouches[0].pageX,w!=K&&(k=s.width(),y=k/r,h.seek(y*z));E=!1}function C(a){a=d+(a.pageX-A);0<a&&a<p&&(q.css("width",a),l.css("left",a-v/2))}function j(a){x.unbind("mousemove",C);b(document).unbind("mouseup",j);L=a.pageX;A!=L&&(d=q.width(),t=d/p,h.setVolume(t),M())}function U(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=d+(e.targetTouches[0].pageX-A),0<a&&a<p&&(q.css("width",a),l.css("left",a-v/2)))}function V(a){e=a.originalEvent;l.unbind("touchmove",
U);l.unbind("touchend",V);if(1==e.changedTouches.length)L=e.changedTouches[0].pageX,A!=L&&(d=q.width(),t=d/p,h.setVolume(t),M())}function M(){0<t?(h.muted(!1),F.show(),B.hide()):(h.muted(!0),F.hide(),B.show())}var x=c.$container,Q=c.$video,R=c.$controlbar,N=c.$playBtn,G=c.$pauseBtn,Y=c.$stopBtn,O=c.$fullscreenBtn,H=c.$normalscreenBtn,F=c.$soundopenBtn,B=c.$soundcloseBtn,q=c.$volumelineVolume,I=c.$volumelineDragger,l=c.$volumelinePoint,Z=c.$playtime,$=c.$totaltime,s=c.$progressPlayedLine,n=c.$progressPlayedPoint,
aa=c.$progressLoadedLine,J=c.$progressSeekLine,ba=c.$buffer,P=c.$bigPlayBtn,h,z=0.1,S=0,W="00:00:00",X="00:00:00",D=0,E=!1,w=0,K=0,k=0,r=0,y=0,T=!0,v=0,p=0,d=0,t=0,A=0,L=0,D=n.width(),r=J.width(),v=l.width(),p=I.width();G.hide();H.hide();B.hide();ba.hide();R.click(function(a){a.originalEvent.stopPropagation()});x.click(function(){T?(R.css("visibility","hidden"),i.hide(),T=!1):(R.css("visibility","visible"),i.show(),T=!0)});N.click(function(){h.play()});G.click(function(){h.pause()});Y.click(function(){h.stop()});
P.click(function(a){a.originalEvent.stopPropagation();h.play()});O.click(function(){O.hide();H.show();var a=x.get(0);a.requestFullscreen?a.requestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():Q.webkitEnterFullscreen?(Q.play(),Q.webkitEnterFullscreen(),O.show(),H.hide()):m.fullScreen("not-support")});H.click(function(){O.show();H.hide();document.exitFullscreen?document.exitFullscreen():
document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():m.normalScreen()});F.click(function(){h.muted(!0);F.hide();B.show();q.css("width",0);l.css("left",-v/2)});B.click(function(){h.muted(!1);F.show();B.hide();q.css("width",d);l.css("left",d-v/2)});J.mousedown(function(a){k=a.pageX-a.target.getBoundingClientRect().left;r=J.width();s.css("width",k);n.css("left",k-D/2);y=k/r;
h.seek(y*z)});n.mousedown(function(a){this.blur();E=!0;w=a.pageX;k=s.width();r=J.width();x.bind("mousemove",o);b(document).bind("mouseup",f)});n.bind("touchstart",function(a){e=a.originalEvent;n.blur();a=e.targetTouches[0];E=!0;w=a.pageX;k=s.width();r=J.width();n.bind("touchmove",u);n.bind("touchend",g)});I.mousedown(function(a){d=a.pageX-a.target.getBoundingClientRect().left;p=I.width();q.css("width",d);l.css("left",d-v/2);t=d/p;h.setVolume(t);M()});l.mousedown(function(a){this.blur();A=a.pageX;
d=q.width();p=I.width();x.bind("mousemove",C);b(document).bind("mouseup",j)});l.bind("touchstart",function(a){e=a.originalEvent;l.blur();A=e.targetTouches[0].pageX;d=q.width();p=I.width();l.bind("touchmove",U);l.bind("touchend",V)});this.setPlayer=function(a){h=a};this.started=function(){N.hide();G.show();P.hide()};this.paused=function(){N.show();G.hide();P.show()};this.stopped=function(){N.show();G.hide();P.show()};this.setDuration=function(a){z=a;X=SewisePlayerSkin.Utils.stringer.secondsToMS(z);
$.text(X)};this.timeUpdate=function(a){S=a;W=SewisePlayerSkin.Utils.stringer.secondsToMS(S);Z.text(W);E||(k=100*(S/z)+"%",s.css("width",k),a=s.width()-D/2,n.css("left",a))};this.loadProgress=function(a){aa.css("width",100*a+"%")};this.initVolume=function(a){t=a;d=p*t;q.css("width",d);l.css("left",d-v/2);M()}}})(window.jQuery);(function(b,c){c(document).ready(function(){var b=SewisePlayer.IVodPlayer,c=new SewisePlayerSkin.ElementObject,o=new SewisePlayerSkin.ElementLayout(c),f=new SewisePlayerSkin.LogoBox(c),u=new SewisePlayerSkin.TopBar(c),g=new SewisePlayerSkin.ControlBar(c,o,u);SewisePlayerSkin.IVodSkin.player=function(c){b=c;g.setPlayer(b)};SewisePlayerSkin.IVodSkin.started=function(){g.started()};SewisePlayerSkin.IVodSkin.paused=function(){g.paused()};SewisePlayerSkin.IVodSkin.stopped=function(){g.stopped()};SewisePlayerSkin.IVodSkin.duration=
function(b){g.setDuration(b)};SewisePlayerSkin.IVodSkin.timeUpdate=function(b){g.timeUpdate(b)};SewisePlayerSkin.IVodSkin.loadedProgress=function(b){g.loadProgress(b)};SewisePlayerSkin.IVodSkin.programTitle=function(b){u.setTitle(b)};SewisePlayerSkin.IVodSkin.logo=function(b){f.setLogo(b)};SewisePlayerSkin.IVodSkin.volume=function(b){g.initVolume(b)};try{SewisePlayer.CommandDispatcher.dispatchEvent({type:SewisePlayer.Events.PLAYER_SKIN_LOADED,playerSkin:SewisePlayerSkin.IVodSkin})}catch(C){console.log("No Main Player")}})})(window,
window.jQuery);
