/*
 * Name: VodFlowPlayer SewisePlayerSkin framework V1.0.0
 * Author: Jack Zhang
 * Website: http://www.sewise.com/
 * Date: 12th June 2014
 * Copyright: 2014, Sewise
 * 
 */


(function(b){b.SewisePlayerSkin={version:"1.0.0"};b.SewisePlayer=b.SewisePlayer||{}})(window);(function(b){b.SewisePlayer.IVodPlayer=b.SewisePlayer.IVodPlayer||{play:function(){},pause:function(){},stop:function(){},seek:function(){},changeClarity:function(){},setVolume:function(){},toPlay:function(){},duration:function(){},playTime:function(){},type:function(){},showTextTip:function(){},hideTextTip:function(){},muted:function(){}}})(window);(function(b){b.SewisePlayerSkin.IVodSkin=b.SewisePlayerSkin.IVodSkin||{player:function(){},started:function(){},paused:function(){},stopped:function(){},seeking:function(){},buffering:function(){},bufferProgress:function(){},loadedProgress:function(){},programTitle:function(){},duration:function(){},playTime:function(){},startTime:function(){},loadSpeed:function(){},initialClarity:function(){},lang:function(){},logo:function(){},timeUpdate:function(){},volume:function(){},clarityButton:function(){},
timeDisplay:function(){},controlBarDisplay:function(){},topBarDisplay:function(){},customStrings:function(){}}})(window);(function(){SewisePlayerSkin.Utils={stringer:{time2FigFill:function(b){var a,b=Math.floor(b);10>b?a="0"+b:a=""+b;return a},secondsToHMS:function(b){if(!(0>b)){var a=this.time2FigFill(Math.floor(b/3600)),g=this.time2FigFill(b/60%60),b=this.time2FigFill(b%60);return a+":"+g+":"+b}},secondsToMS:function(b){if(!(0>b)){var a=this.time2FigFill(b/60),b=this.time2FigFill(b%60);return a+":"+b}},dateToTimeString:function(b){var a;a=b?b:new Date;var b=a.getFullYear(),g=a.getMonth()+1,f=a.getDate(),k=this.time2FigFill(a.getHours()),
c=this.time2FigFill(a.getMinutes());a=this.time2FigFill(a.getSeconds());return b+"-"+g+"-"+f+" "+k+":"+c+":"+a},dateToTimeStr14:function(b){var a=b.getFullYear(),g=this.time2FigFill(b.getMonth()+1),f=this.time2FigFill(b.getDate()),k=this.time2FigFill(b.getHours()),c=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+g+f+k+c+b},dateToStrHMS:function(b){var a=this.time2FigFill(b.getHours()),g=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+
":"+g+":"+b}}}})();(function(b){SewisePlayerSkin.ElementObject=function(){this.$sewisePlayerUi=b(".sewise-player-ui");this.$container=this.$sewisePlayerUi.parent();this.$video=this.$container.find("video").get(0);this.$controlbar=this.$sewisePlayerUi.find(".controlbar");this.$playBtn=this.$sewisePlayerUi.find(".controlbar-btns-play");this.$pauseBtn=this.$sewisePlayerUi.find(".controlbar-btns-pause");this.$stopBtn=this.$sewisePlayerUi.find(".controlbar-btns-stop");this.$fullscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-fullscreen");
this.$normalscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-normalscreen");this.$soundopenBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundopen");this.$soundcloseBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundclose");this.$volumelineVolume=this.$sewisePlayerUi.find(".controlbar-volumeline-volume");this.$volumelineDragger=this.$sewisePlayerUi.find(".controlbar-volumeline-dragger");this.$volumelinePoint=this.$sewisePlayerUi.find(".controlbar-volumeline-point");this.$playtime=this.$sewisePlayerUi.find(".controlbar-playtime");
this.$totaltime=this.$sewisePlayerUi.find(".controlbar-totaltime");this.$controlBarProgress=this.$sewisePlayerUi.find(".controlbar-progress");this.$progressPlayedLine=this.$sewisePlayerUi.find(".controlbar-progress-playedline");this.$progressPlayedPoint=this.$sewisePlayerUi.find(".controlbar-progress-playpoint");this.$progressLoadedLine=this.$sewisePlayerUi.find(".controlbar-progress-loadedline");this.$progressSeekLine=this.$sewisePlayerUi.find(".controlbar-progress-seekline");this.$logo=this.$sewisePlayerUi.find(".logo");
this.$logoIcon=this.$sewisePlayerUi.find(".logo-icon");this.$topbar=this.$sewisePlayerUi.find(".topbar");this.$programTitle=this.$sewisePlayerUi.find(".topbar-program-title");this.$topbarClock=this.$sewisePlayerUi.find(".topbar-clock");this.$buffer=this.$sewisePlayerUi.find(".buffer");this.$bigPlayBtn=this.$sewisePlayerUi.find(".big-play-btn");this.$claritySwitchBtn=this.$sewisePlayerUi.find(".clarity-switch-btn");this.$clarityBtnText=this.$sewisePlayerUi.find(".clarity-btn-text");this.defStageWidth=
this.$container.width();this.defStageHeight=this.$container.height();this.defLeftValue=parseInt(this.$container.css("left"));this.defTopValue=parseInt(this.$container.css("top"));this.defOffsetX=this.$container.get(0).getBoundingClientRect().left;this.defOffsetY=this.$container.get(0).getBoundingClientRect().top;this.defOverflow=b("body").css("overflow")}})(window.jQuery);(function(b){SewisePlayerSkin.ElementLayout=function(a){function g(){null!=document.fullscreenElement||null!=document.msFullscreenElement||null!=document.mozFullScreenElement||null!=document.webkitFullscreenElement?p.fullScreen():p.normalScreen()}var f=a.$container,k=a.$controlBarProgress,c=a.$playtime,p=this,m=a.defStageWidth,d=a.defStageHeight,v=a.defLeftValue,i=a.defTopValue,r=a.defOffsetX,M=a.defOffsetY,s=a.defOverflow,j=parseInt(m)-265;0>j&&(j+=c.width(),c.hide());k.css("width",j);document.addEventListener("fullscreenchange",
g);document.addEventListener("MSFullscreenChange",g);document.addEventListener("mozfullscreenchange",g);document.addEventListener("webkitfullscreenchange",g);this.fullScreen=function(a){if("not-support"==a){var a=b(window).width(),d=b(window).height()-8;f.css("width",a);f.css("height",d);a=i-M+"px";f.css("left",v-r+"px");f.css("top",a);b("body").css("overflow","hidden")}else f.css("width","100%"),f.css("height","100%");a=parseInt(f.width())-265;0>a?(a+=c.width(),c.hide()):c.show();k.css("width",a)};
this.normalScreen=function(){f.css("width",m);f.css("height",d);f.css("left",v);f.css("top",i);b("body").css("overflow",s);j=parseInt(m)-265;0>j?(j+=c.width(),c.hide()):c.show();k.css("width",j)}}})(window.jQuery);(function(){SewisePlayerSkin.LogoBox=function(b){var a=b.$logoIcon;this.setLogo=function(b){a.css("background","url("+b+") 0px 0px no-repeat");a.attr("href","http://www.sewise.com/")}}})(window.jQuery);(function(){SewisePlayerSkin.TopBar=function(b){var a=b.$topbar,g=b.$programTitle,f=b.$topbarClock;setInterval(function(){var a=SewisePlayerSkin.Utils.stringer.dateToTimeString();f.text(a)},1E3);this.setTitle=function(a){g.text(a)};this.show=function(){a.css("visibility","visible")};this.hide=function(){a.css("visibility","hidden")};this.hide2=function(){a.hide()}}})(window.jQuery);(function(b){SewisePlayerSkin.ClarityWindow=function(a){var g=a.$container,f,k,c,p="",m="",d,v,i=0,r=0;this.setPlayer=function(a){f=a};this.setControlBar=function(a){k=a};this.initialClarities=function(a){d=a;v=d.length;for(a=0;a<v;a++){var s;d[a].selected?(s=' checked = "checked" ',i=a,k.updateClarityBtnText(d[a].name)):s=" ";p+='<input style="width: 20px; height: 18px; " type="radio" name="radio_clarity"'+s+'"value="'+d[a].name+'">'+d[a].name+"\n"}m='<div style="position:absolute; width: 300px; height: 140px; color: #FFF; border: 2px solid #FF9501; padding: 10px; background: rgba(255, 149, 1, 0.3); "><div><div style="float: left; ">\u6e05\u6670\u5ea6\u8bbe\u7f6e</div><div style="float: right; "><a href="javascript:;" name="cancel_clarity" style="color: #FFF; font-weight:bold; text-decoration: none; padding: 4px 6px; ">X</a></div></div><div style="width: 100%; height: 40px; padding: 30px 0px 10px 0px; text-align: center; clear: both;">'+
p+'</div><div style="padding: 10px; text-align: center; "><a href="javascript:;" name="confirm_clarity" style="color: #FFF; text-decoration: none; background-color: #FF9501; padding: 5px 10px; margin-right: 20px; ">\u786e\u5b9a</a><a href="javascript:;" name="cancel_clarity" style="color: #FFF; text-decoration: none; background-color: #FF9501; padding: 5px 10px; margin-left: 20px; ">\u53d6\u6d88</a></div><div>';c=b("<div></div>");c.html(m);c.css({position:"absolute",left:"50%",top:"50%","margin-left":"-162px",
"margin-top":"-82px"});c.hide();c.appendTo(g);c.click(function(a){a.originalEvent.stopPropagation()});c.find("[name = confirm_clarity]").click(function(a){a.originalEvent.stopPropagation();c.hide();i!=r&&(i=r,k.updateClarityBtnText(d[i].name),f.changeClarity({name:d[i].name,videoUrl:d[i].videoUrl,id:d[i].id,selected:!0}))});c.find("[name = cancel_clarity]").click(function(a){a.originalEvent.stopPropagation();c.hide();r=i});c.find("[name = radio_clarity]").click(function(a){a.originalEvent.stopPropagation();
r=b(a.target).index()})};this.toggle=function(){c.toggle();c.find("[name = radio_clarity]").get(i).checked=!0;r=i}}})(window.jQuery);(function(b){SewisePlayerSkin.ControlBar=function(a,g,f,k){function c(a){a=n+(a.pageX-A);0<a&&a<w&&(x.css("width",a),q.css("left",a-F/2))}function p(a){j.unbind("mousemove",c);b(document).unbind("mouseup",p);O=a.pageX;A!=O&&(n=x.width(),B=n/w,l.seek(B*C));G=!1}function m(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=n+(e.targetTouches[0].pageX-A),0<a&&a<w&&(x.css("width",a),q.css("left",a-F/2)))}function d(a){e=a.originalEvent;q.unbind("touchmove",m);q.unbind("touchend",d);
if(1==e.changedTouches.length)O=e.changedTouches[0].pageX,A!=O&&(n=x.width(),B=n/w,l.seek(B*C));G=!1}function v(a){a=h+(a.pageX-D);0<a&&a<t&&(u.css("width",a),o.css("left",a-z/2))}function i(a){j.unbind("mousemove",v);b(document).unbind("mouseup",i);P=a.pageX;D!=P&&(h=u.width(),y=h/t,l.setVolume(y),s())}function r(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=h+(e.targetTouches[0].pageX-D),0<a&&a<t&&(u.css("width",a),o.css("left",a-z/2)))}function M(a){e=a.originalEvent;o.unbind("touchmove",
r);o.unbind("touchend",M);if(1==e.changedTouches.length)P=e.changedTouches[0].pageX,D!=P&&(h=u.width(),y=h/t,l.setVolume(y),s())}function s(){0<y?(l.muted(!1),H.show(),E.hide()):(l.muted(!0),H.hide(),E.show())}var j=a.$container,U=a.$video,N=a.$controlbar,Q=a.$playBtn,I=a.$pauseBtn,Z=a.$stopBtn,R=a.$fullscreenBtn,J=a.$normalscreenBtn,H=a.$soundopenBtn,E=a.$soundcloseBtn,u=a.$volumelineVolume,K=a.$volumelineDragger,o=a.$volumelinePoint,$=a.$playtime,aa=a.$totaltime,x=a.$progressPlayedLine,q=a.$progressPlayedPoint,
ba=a.$progressLoadedLine,L=a.$progressSeekLine,ca=a.$buffer,S=a.$bigPlayBtn,T=a.$claritySwitchBtn,da=a.$clarityBtnText,l,C=0.1,V=0,X="00:00:00",Y="00:00:00",F=0,G=!1,A=0,O=0,n=0,w=0,B=0,W=!0,z=0,t=0,h=0,y=0,D=0,P=0,F=q.width(),w=L.width(),z=o.width(),t=K.width();I.hide();J.hide();E.hide();ca.hide();N.click(function(a){a.originalEvent.stopPropagation()});j.click(function(){W?(N.css("visibility","hidden"),f.hide(),W=!1):(N.css("visibility","visible"),f.show(),W=!0)});Q.click(function(){l.play()});I.click(function(){l.pause()});
Z.click(function(){l.stop()});S.click(function(a){a.originalEvent.stopPropagation();l.play()});R.click(function(){R.hide();J.show();var a=j.get(0);a.requestFullscreen?a.requestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():U.webkitEnterFullscreen?(U.play(),U.webkitEnterFullscreen(),R.show(),J.hide()):g.fullScreen("not-support")});J.click(function(){R.show();J.hide();document.exitFullscreen?
document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():g.normalScreen()});H.click(function(){l.muted(!0);H.hide();E.show();u.css("width",0);o.css("left",-z/2)});E.click(function(){l.muted(!1);H.show();E.hide();u.css("width",h);o.css("left",h-z/2)});T.click(function(a){a.originalEvent.stopPropagation();k.toggle()});L.mousedown(function(a){n=a.pageX-
a.target.getBoundingClientRect().left;w=L.width();x.css("width",n);q.css("left",n-F/2);B=n/w;l.seek(B*C)});q.mousedown(function(a){this.blur();G=!0;A=a.pageX;n=x.width();w=L.width();j.bind("mousemove",c);b(document).bind("mouseup",p)});q.bind("touchstart",function(a){e=a.originalEvent;q.blur();a=e.targetTouches[0];G=!0;A=a.pageX;n=x.width();w=L.width();q.bind("touchmove",m);q.bind("touchend",d)});K.mousedown(function(a){h=a.pageX-a.target.getBoundingClientRect().left;t=K.width();u.css("width",h);
o.css("left",h-z/2);y=h/t;l.setVolume(y);s()});o.mousedown(function(a){this.blur();D=a.pageX;h=u.width();t=K.width();j.bind("mousemove",v);b(document).bind("mouseup",i)});o.bind("touchstart",function(a){e=a.originalEvent;o.blur();D=e.targetTouches[0].pageX;h=u.width();t=K.width();o.bind("touchmove",r);o.bind("touchend",M)});this.setPlayer=function(a){l=a};this.started=function(){Q.hide();I.show();S.hide()};this.paused=function(){Q.show();I.hide();S.show()};this.stopped=function(){Q.show();I.hide();
S.show()};this.setDuration=function(a){C=a;Y=SewisePlayerSkin.Utils.stringer.secondsToMS(C);aa.text(Y)};this.timeUpdate=function(a){V=a;X=SewisePlayerSkin.Utils.stringer.secondsToMS(V);$.text(X);G||(n=100*(V/C)+"%",x.css("width",n),a=x.width()-F/2,q.css("left",a))};this.loadProgress=function(a){ba.css("width",100*a+"%")};this.initVolume=function(a){y=a;h=t*y;u.css("width",h);o.css("left",h-z/2);s()};this.hide2=function(){N.hide()};this.hideClarityBtn=function(){T.hide()};this.updateClarityBtnPosition=
function(){T.css("top","0%");T.css("margin-top","0px")};this.updateClarityBtnText=function(a){da.text(a)}}})(window.jQuery);(function(b,a){a(document).ready(function(){var a=SewisePlayer.IVodPlayer,b=new SewisePlayerSkin.ElementObject,k=new SewisePlayerSkin.ElementLayout(b),c=new SewisePlayerSkin.LogoBox(b),p=new SewisePlayerSkin.TopBar(b),m=new SewisePlayerSkin.ClarityWindow(b),d=new SewisePlayerSkin.ControlBar(b,k,p,m);SewisePlayerSkin.IVodSkin.player=function(b){a=b;d.setPlayer(a);m.setPlayer(a)};SewisePlayerSkin.IVodSkin.started=function(){d.started()};SewisePlayerSkin.IVodSkin.paused=function(){d.paused()};SewisePlayerSkin.IVodSkin.stopped=
function(){d.stopped()};SewisePlayerSkin.IVodSkin.duration=function(a){d.setDuration(a)};SewisePlayerSkin.IVodSkin.timeUpdate=function(a){d.timeUpdate(a)};SewisePlayerSkin.IVodSkin.loadedProgress=function(a){d.loadProgress(a)};SewisePlayerSkin.IVodSkin.programTitle=function(a){p.setTitle(a)};SewisePlayerSkin.IVodSkin.logo=function(a){c.setLogo(a)};SewisePlayerSkin.IVodSkin.volume=function(a){d.initVolume(a)};SewisePlayerSkin.IVodSkin.initialClarity=function(a){m.setControlBar(d);m.initialClarities(a)};
SewisePlayerSkin.IVodSkin.clarityButton=function(a){"enable"!=a&&d.hideClarityBtn()};SewisePlayerSkin.IVodSkin.timeDisplay=function(){};SewisePlayerSkin.IVodSkin.controlBarDisplay=function(a){"enable"!=a&&d.hide2()};SewisePlayerSkin.IVodSkin.topBarDisplay=function(a){"enable"!=a&&(p.hide2(),d.updateClarityBtnPosition())};SewisePlayerSkin.IVodSkin.customStrings=function(){};try{SewisePlayer.CommandDispatcher.dispatchEvent({type:SewisePlayer.Events.PLAYER_SKIN_LOADED,playerSkin:SewisePlayerSkin.IVodSkin})}catch(v){console.log("No Main Player")}})})(window,
window.jQuery);
