/*
 * Name: LiveWhite SewisePlayerSkin framework V1.0.0
 * Author: Jack Zhang
 * Website: http://www.sewise.com/
 * Date: 24th March 2014
 * Copyright: 2014, Sewise
 * 
 */


(function(b){b.SewisePlayerSkin={version:"1.0.0"};b.SewisePlayer=b.SewisePlayer||{}})(window);(function(b){b.SewisePlayer.ILivePlayer=b.SewisePlayer.ILivePlayer||{live:function(){},play:function(){},pause:function(){},stop:function(){},seek:function(){},changeClarity:function(){},setVolume:function(){},playChannel:function(){},toPlay:function(){},duration:function(){},liveTime:function(){},playTime:function(){},type:function(){},showTextTip:function(){},hideTextTip:function(){},muted:function(){}}})(window);(function(b){b.SewisePlayerSkin.ILiveSkin=b.SewisePlayerSkin.ILiveSkin||{player:function(){},started:function(){},paused:function(){},stopped:function(){},seeking:function(){},buffering:function(){},bufferProgress:function(){},programTitle:function(){},duration:function(){},playTime:function(){},startTime:function(){},loadSpeed:function(){},initialClarity:function(){},lang:function(){},logo:function(){},timeUpdate:function(){},volume:function(){},clarityButton:function(){},timeDisplay:function(){},
controlBarDisplay:function(){},topBarDisplay:function(){},customStrings:function(){},fullScreen:function(){},noramlScreen:function(){}}})(window);(function(){SewisePlayerSkin.Utils={stringer:{time2FigFill:function(b){var a,b=Math.floor(b);10>b?a="0"+b:a=""+b;return a},secondsToHMS:function(b){if(!(0>b)){var a=this.time2FigFill(Math.floor(b/3600)),d=this.time2FigFill(b/60%60),b=this.time2FigFill(b%60);return a+":"+d+":"+b}},secondsToMS:function(b){if(!(0>b)){var a=this.time2FigFill(b/60),b=this.time2FigFill(b%60);return a+":"+b}},dateToTimeString:function(b){var a;a=b?b:new Date;var b=a.getFullYear(),d=a.getMonth()+1,c=a.getDate(),k=this.time2FigFill(a.getHours()),
f=this.time2FigFill(a.getMinutes());a=this.time2FigFill(a.getSeconds());return b+"-"+d+"-"+c+" "+k+":"+f+":"+a},dateToTimeStr14:function(b){var a=b.getFullYear(),d=this.time2FigFill(b.getMonth()+1),c=this.time2FigFill(b.getDate()),k=this.time2FigFill(b.getHours()),f=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+d+c+k+f+b},dateToStrHMS:function(b){var a=this.time2FigFill(b.getHours()),d=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+
":"+d+":"+b}}}})();(function(b){SewisePlayerSkin.ElementObject=function(){this.$sewisePlayerUi=b(".sewise-player-ui");this.$container=this.$sewisePlayerUi.parent();this.$video=this.$container.find("video").get(0);this.$controlbar=this.$sewisePlayerUi.find(".controlbar");this.$playBtn=this.$sewisePlayerUi.find(".controlbar-btns-play");this.$pauseBtn=this.$sewisePlayerUi.find(".controlbar-btns-pause");this.$liveBtn=this.$sewisePlayerUi.find(".controlbar-btns-live");this.$fullscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-fullscreen");
this.$normalscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-normalscreen");this.$soundopenBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundopen");this.$soundcloseBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundclose");this.$shareBtn=this.$sewisePlayerUi.find(".controlbar-btns-share");this.$playtime=this.$sewisePlayerUi.find(".controlbar-playtime");this.$controlBarProgress=this.$sewisePlayerUi.find(".controlbar-progress");this.$progressPlayedLine=this.$sewisePlayerUi.find(".controlbar-progress-playedline");
this.$progressPlayedPoint=this.$sewisePlayerUi.find(".controlbar-progress-playpoint");this.$progressLoadedLine=this.$sewisePlayerUi.find(".controlbar-progress-loadedline");this.$progressSeekLine=this.$sewisePlayerUi.find(".controlbar-progress-seekline");this.$logo=this.$sewisePlayerUi.find(".logo");this.$logoIcon=this.$sewisePlayerUi.find(".logo-icon");this.$topbar=this.$sewisePlayerUi.find(".topbar");this.$programTitle=this.$sewisePlayerUi.find(".topbar-program-title");this.$topbarClock=this.$sewisePlayerUi.find(".topbar-clock");
this.$buffer=this.$sewisePlayerUi.find(".buffer");this.$bigPlayBtn=this.$sewisePlayerUi.find(".big-play-btn");this.defStageWidth=this.$container.width();this.defStageHeight=this.$container.height();this.defLeftValue=parseInt(this.$container.css("left"));this.defTopValue=parseInt(this.$container.css("top"));this.defOffsetX=this.$container.get(0).getBoundingClientRect().left;this.defOffsetY=this.$container.get(0).getBoundingClientRect().top;this.defOverflow=b("body").css("overflow")}})(window.jQuery);(function(b){SewisePlayerSkin.ElementLayout=function(a){function d(){null!=document.fullscreenElement||null!=document.msFullscreenElement||null!=document.mozFullScreenElement||null!=document.webkitFullscreenElement?m.fullScreen():m.normalScreen()}var c=a.$container,k=a.$controlBarProgress,f=a.$playtime,m=this,g=a.defStageWidth,t=a.defStageHeight,q=a.defLeftValue,r=a.defTopValue,u=a.defOffsetX,s=a.defOffsetY,E=a.defOverflow,j=parseInt(g)-288;0>j&&(j+=f.width(),f.hide());k.css("width",j);document.addEventListener("fullscreenchange",
d);document.addEventListener("MSFullscreenChange",d);document.addEventListener("mozfullscreenchange",d);document.addEventListener("webkitfullscreenchange",d);this.fullScreen=function(a){if("not-support"==a){var a=b(window).width(),d=b(window).height()-8;c.css("width",a);c.css("height",d);a=r-s+"px";c.css("left",q-u+"px");c.css("top",a);b("body").css("overflow","hidden")}else c.css("width","100%"),c.css("height","100%");a=parseInt(c.width())-288;0>a?(a+=f.width(),f.hide()):f.show();k.css("width",a)};
this.normalScreen=function(){c.css("width",g);c.css("height",t);c.css("left",q);c.css("top",r);b("body").css("overflow",E);j=parseInt(g)-288;0>j?(j+=f.width(),f.hide()):f.show();k.css("width",j)}}})(window.jQuery);(function(){SewisePlayerSkin.LogoBox=function(b){var a=b.$logoIcon;this.setLogo=function(b){a.css("background","url("+b+") 0px 0px no-repeat");a.attr("href","http://www.sewise.com/")}}})(window.jQuery);(function(){SewisePlayerSkin.TopBar=function(b){var a=b.$topbar,d=b.$programTitle,c=b.$topbarClock;this.setClock=function(a){a=SewisePlayerSkin.Utils.stringer.dateToTimeString(a);c.text(a)};this.setTitle=function(a){d.text(a)};this.show=function(){a.css("visibility","visible")};this.hide=function(){a.css("visibility","hidden")};this.hide2=function(){a.hide()}}})(window.jQuery);(function(b){SewisePlayerSkin.ControlBar=function(a,d,c){function k(a){a=i+(a.pageX-v);0<a&&a<o&&(p.css("width",a),l.css("left",a-x/2))}function f(a){q.unbind("mousemove",k);b(document).unbind("mouseup",f);B=a.pageX;v!=B&&(i=p.width(),w=i/o,t(w));y=!1}function m(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=i+(e.targetTouches[0].pageX-v),0<a&&a<o&&(p.css("width",a),l.css("left",a-x/2)))}function g(a){e=a.originalEvent;l.unbind("touchmove",m);l.unbind("touchend",g);if(1==e.changedTouches.length)B=
e.changedTouches[0].pageX,v!=B&&(i=p.width(),w=i/o,t(w));y=!1}function t(a){a=new Date(36E5*Math.floor(h.playTime().getTime()/1E3/3600)+1E3*a*n);a=SewisePlayerSkin.Utils.stringer.dateToTimeStr14(a);h.seek(a)}var q=a.$container,r=a.$controlbar,u=a.$playBtn,s=a.$pauseBtn,E=a.$liveBtn,j=a.$fullscreenBtn,A=a.$normalscreenBtn,F=a.$soundopenBtn,C=a.$soundcloseBtn,K=a.$playtime,p=a.$progressPlayedLine,l=a.$progressPlayedPoint,L=a.$progressLoadedLine,z=a.$progressSeekLine,M=a.$buffer,D=a.$bigPlayBtn,H=this,
h,n=0.1,I="00:00:00",J="00:00:00",x=0,y=!1,v=0,B=0,i=0,o=0,w=0,G=!0,x=l.width(),o=z.width();s.hide();A.hide();C.hide();M.hide();r.click(function(a){a.originalEvent.stopPropagation()});q.click(function(){G?(r.css("visibility","hidden"),c.hide(),G=!1):(r.css("visibility","visible"),c.show(),G=!0)});u.click(function(){h.play()});s.click(function(){h.pause()});E.click(function(){h.live()});D.click(function(a){a.originalEvent.stopPropagation();h.play()});j.click(function(){H.fullScreen()});A.click(function(){H.noramlScreen()});
F.click(function(){h.muted(!0);F.hide();C.show()});C.click(function(){h.muted(!1);F.show();C.hide()});z.mousedown(function(a){i=a.pageX-a.target.getBoundingClientRect().left;o=z.width();p.css("width",i);l.css("left",i-x/2);w=i/o;t(w)});l.mousedown(function(a){this.blur();y=!0;v=a.pageX;i=p.width();o=z.width();q.bind("mousemove",k);b(document).bind("mouseup",f)});l.bind("touchstart",function(a){e=a.originalEvent;l.blur();a=e.targetTouches[0];y=!0;v=a.pageX;i=p.width();o=z.width();l.bind("touchmove",
m);l.bind("touchend",g)});this.setPlayer=function(a){h=a};this.started=function(){u.hide();s.show();D.hide()};this.paused=function(){u.show();s.hide();D.show()};this.stopped=function(){u.show();s.hide();D.show()};this.setDuration=function(a){n=a};this.timeUpdate=function(){if(h.playTime()&&(J=SewisePlayerSkin.Utils.stringer.dateToStrHMS(new Date(1E3*Math.ceil(h.playTime().getTime()/1E3/n)*n)),I=SewisePlayerSkin.Utils.stringer.dateToStrHMS(new Date(1E3*Math.floor(h.playTime().getTime()/1E3/n)*n)),
K.text(I+"/"+J),!y)){i=100*(Math.floor(h.playTime().getTime()/1E3)%n/n)+"%";p.css("width",i);var a=p.width()-x/2;l.css("left",a);a=Math.ceil(h.playTime().getTime()/1E3/3600);a=100*(Math.floor(h.liveTime().getTime()/1E3/3600)>=a?1:Math.floor(h.liveTime().getTime()/1E3)%n/n)+"%";L.css("width",a)}};this.hide2=function(){r.hide()};this.fullScreen=function(){j.hide();A.show();var a=q.get(0);a.requestFullscreen?a.requestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():
a.webkitRequestFullscreen?a.webkitRequestFullscreen():d.fullScreen("not-support")};this.noramlScreen=function(){j.show();A.hide();document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():d.normalScreen()}}})(window.jQuery);(function(b,a){a(document).ready(function(){var a=SewisePlayer.ILivePlayer,b=new SewisePlayerSkin.ElementObject,k=new SewisePlayerSkin.ElementLayout(b),f=new SewisePlayerSkin.LogoBox(b),m=new SewisePlayerSkin.TopBar(b),g=new SewisePlayerSkin.ControlBar(b,k,m);SewisePlayerSkin.ILiveSkin.player=function(b){a=b;g.setPlayer(a)};SewisePlayerSkin.ILiveSkin.started=function(){g.started()};SewisePlayerSkin.ILiveSkin.paused=function(){g.paused()};SewisePlayerSkin.ILiveSkin.stopped=function(){g.stopped()};
SewisePlayerSkin.ILiveSkin.duration=function(a){g.setDuration(a)};SewisePlayerSkin.ILiveSkin.timeUpdate=function(){g.timeUpdate();m.setClock(a.playTime())};SewisePlayerSkin.ILiveSkin.programTitle=function(a){m.setTitle(a)};SewisePlayerSkin.ILiveSkin.logo=function(a){f.setLogo(a)};SewisePlayerSkin.ILiveSkin.volume=function(){};SewisePlayerSkin.ILiveSkin.clarityButton=function(){};SewisePlayerSkin.ILiveSkin.timeDisplay=function(){};SewisePlayerSkin.ILiveSkin.controlBarDisplay=function(a){"enable"!=
a&&g.hide2()};SewisePlayerSkin.ILiveSkin.topBarDisplay=function(a){"enable"!=a&&m.hide2()};SewisePlayerSkin.ILiveSkin.customStrings=function(){};SewisePlayerSkin.ILiveSkin.fullScreen=function(){g.fullScreen()};SewisePlayerSkin.ILiveSkin.noramlScreen=function(){g.noramlScreen()};try{SewisePlayer.CommandDispatcher.dispatchEvent({type:SewisePlayer.Events.PLAYER_SKIN_LOADED,playerSkin:SewisePlayerSkin.ILiveSkin})}catch(t){console.log("No Main Player")}})})(window,window.jQuery);
