/*
 * Name: LiveWhite SewisePlayerSkin framework V1.0.0
 * Author: Jack Zhang
 * Website: http://www.sewise.com/
 * Date: 24th March 2014
 * Copyright: 2014, Sewise
 * 
 */


(function(a){a.SewisePlayerSkin={version:"1.0.0"};a.SewisePlayer=a.SewisePlayer||{}})(window);(function(a){a.SewisePlayer.ILivePlayer=a.SewisePlayer.ILivePlayer||{live:function(){},play:function(){},pause:function(){},stop:function(){},seek:function(){},changeClarity:function(){},setVolume:function(){},playChannel:function(){},toPlay:function(){},duration:function(){},liveTime:function(){},playTime:function(){},type:function(){},showTextTip:function(){},hideTextTip:function(){},muted:function(){}}})(window);(function(a){a.SewisePlayerSkin.ILiveSkin=a.SewisePlayerSkin.ILiveSkin||{player:function(){},started:function(){},paused:function(){},stopped:function(){},seeking:function(){},buffering:function(){},bufferProgress:function(){},programTitle:function(){},duration:function(){},playTime:function(){},startTime:function(){},loadSpeed:function(){},initialClarity:function(){},lang:function(){},logo:function(){},clarityButton:function(){},timeDisplay:function(){},controlBarDisplay:function(){},topBarDisplay:function(){},
timeUpdate:function(){},volume:function(){},clarityButton:function(){},timeDisplay:function(){},controlBarDisplay:function(){},topBarDisplay:function(){},customStrings:function(){}}})(window);(function(){SewisePlayerSkin.Utils={stringer:{time2FigFill:function(a){var b,a=Math.floor(a);10>a?b="0"+a:b=""+a;return b},secondsToHMS:function(a){if(!(0>a)){var b=this.time2FigFill(Math.floor(a/3600)),c=this.time2FigFill(a/60%60),a=this.time2FigFill(a%60);return b+":"+c+":"+a}},secondsToMS:function(a){if(!(0>a)){var b=this.time2FigFill(a/60),a=this.time2FigFill(a%60);return b+":"+a}},dateToTimeString:function(a){var b;b=a?a:new Date;var a=b.getFullYear(),c=b.getMonth()+1,f=b.getDate(),k=this.time2FigFill(b.getHours()),
d=this.time2FigFill(b.getMinutes());b=this.time2FigFill(b.getSeconds());return a+"-"+c+"-"+f+" "+k+":"+d+":"+b},dateToTimeStr14:function(a){var b=a.getFullYear(),c=this.time2FigFill(a.getMonth()+1),f=this.time2FigFill(a.getDate()),k=this.time2FigFill(a.getHours()),d=this.time2FigFill(a.getMinutes()),a=this.time2FigFill(a.getSeconds());return b+c+f+k+d+a},dateToStrHMS:function(a){var b=this.time2FigFill(a.getHours()),c=this.time2FigFill(a.getMinutes()),a=this.time2FigFill(a.getSeconds());return b+
":"+c+":"+a}}}})();(function(a){SewisePlayerSkin.ElementObject=function(){this.$sewisePlayerUi=a(".sewise-player-ui");this.$container=this.$sewisePlayerUi.parent();this.$video=this.$container.find("video").get(0);this.$controlbar=this.$sewisePlayerUi.find(".controlbar");this.$playBtn=this.$sewisePlayerUi.find(".controlbar-btns-play");this.$pauseBtn=this.$sewisePlayerUi.find(".controlbar-btns-pause");this.$liveBtn=this.$sewisePlayerUi.find(".controlbar-btns-live");this.$fullscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-fullscreen");
this.$normalscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-normalscreen");this.$soundopenBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundopen");this.$soundcloseBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundclose");this.$shareBtn=this.$sewisePlayerUi.find(".controlbar-btns-share");this.$playtime=this.$sewisePlayerUi.find(".controlbar-playtime");this.$controlBarProgress=this.$sewisePlayerUi.find(".controlbar-progress");this.$progressPlayedLine=this.$sewisePlayerUi.find(".controlbar-progress-playedline");
this.$progressPlayedPoint=this.$sewisePlayerUi.find(".controlbar-progress-playpoint");this.$progressLoadedLine=this.$sewisePlayerUi.find(".controlbar-progress-loadedline");this.$progressSeekLine=this.$sewisePlayerUi.find(".controlbar-progress-seekline");this.$logo=this.$sewisePlayerUi.find(".logo");this.$logoIcon=this.$sewisePlayerUi.find(".logo-icon");this.$topbar=this.$sewisePlayerUi.find(".topbar");this.$programTitle=this.$sewisePlayerUi.find(".topbar-program-title");this.$topbarClock=this.$sewisePlayerUi.find(".topbar-clock");
this.$buffer=this.$sewisePlayerUi.find(".buffer");this.$bigPlayBtn=this.$sewisePlayerUi.find(".big-play-btn");this.defStageWidth=this.$container.width();this.defStageHeight=this.$container.height()}})(window.jQuery);(function(a){SewisePlayerSkin.ElementLayout=function(b){function c(){null!=document.fullscreenElement||null!=document.msFullscreenElement||null!=document.mozFullScreenElement||null!=document.webkitFullscreenElement?m.fullScreen():m.normalScreen()}var f=b.$container,k=b.$controlBarProgress,d=b.$playtime,m=this,i=b.defStageWidth,q=b.defStageHeight,g=parseInt(i)-288;0>g&&(g+=d.width(),d.hide());k.css("width",g);document.addEventListener("fullscreenchange",c);document.addEventListener("MSFullscreenChange",
c);document.addEventListener("mozfullscreenchange",c);document.addEventListener("webkitfullscreenchange",c);this.fullScreen=function(b){if("not-support"==b){var b=a(window).width()-15,g=a(window).height()-15;f.css("width",b);f.css("height",g)}else f.css("width","100%"),f.css("height","100%");b=parseInt(f.width())-288;0>b?(b+=d.width(),d.hide()):d.show();k.css("width",b)};this.normalScreen=function(){f.css("width",i);f.css("height",q);g=parseInt(i)-288;0>g?(g+=d.width(),d.hide()):d.show();k.css("width",
g)}}})(window.jQuery);(function(){SewisePlayerSkin.LogoBox=function(a){var b=a.$logoIcon;this.setLogo=function(a){b.css("background","url("+a+") 0px 0px no-repeat");b.attr("href","http://www.sewise.com/")}}})(window.jQuery);(function(){SewisePlayerSkin.TopBar=function(a){var b=a.$topbar,c=a.$programTitle,f=a.$topbarClock;this.setClock=function(a){a=SewisePlayerSkin.Utils.stringer.dateToTimeString(a);f.text(a)};this.setTitle=function(a){c.text(a)};this.show=function(){b.css("visibility","visible")};this.hide=function(){b.css("visibility","hidden")};this.hide2=function(){b.hide()}}})(window.jQuery);(function(a){SewisePlayerSkin.ControlBar=function(b,c,f){function k(a){a=j+(a.pageX-r);0<a&&a<o&&(p.css("width",a),l.css("left",a-t/2))}function d(b){g.unbind("mousemove",k);a(document).unbind("mouseup",d);z=b.pageX;r!=z&&(j=p.width(),s=j/o,q(s));u=!1}function m(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=j+(e.targetTouches[0].pageX-r),0<a&&a<o&&(p.css("width",a),l.css("left",a-t/2)))}function i(a){e=a.originalEvent;l.unbind("touchmove",m);l.unbind("touchend",i);if(1==e.changedTouches.length)z=
e.changedTouches[0].pageX,r!=z&&(j=p.width(),s=j/o,q(s));u=!1}function q(a){a=new Date(36E5*Math.floor(h.playTime().getTime()/1E3/3600)+1E3*a*n);a=SewisePlayerSkin.Utils.stringer.dateToTimeStr14(a);h.seek(a)}var g=b.$container,x=b.$controlbar,y=b.$playBtn,v=b.$pauseBtn,I=b.$liveBtn,D=b.$fullscreenBtn,A=b.$normalscreenBtn,E=b.$soundopenBtn,B=b.$soundcloseBtn,J=b.$playtime,p=b.$progressPlayedLine,l=b.$progressPlayedPoint,K=b.$progressLoadedLine,w=b.$progressSeekLine,L=b.$buffer,C=b.$bigPlayBtn,h,n=
0.1,G="00:00:00",H="00:00:00",t=0,u=!1,r=0,z=0,j=0,o=0,s=0,F=!0,t=l.width(),o=w.width();v.hide();A.hide();B.hide();L.hide();x.click(function(a){a.originalEvent.stopPropagation()});g.click(function(){F?(x.css("visibility","hidden"),f.hide(),F=!1):(x.css("visibility","visible"),f.show(),F=!0)});y.click(function(){h.play()});v.click(function(){h.pause()});I.click(function(){h.live()});C.click(function(a){a.originalEvent.stopPropagation();h.play()});D.click(function(){D.hide();A.show();var a=g.get(0);
a.requestFullscreen?a.requestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():c.fullScreen("not-support")});A.click(function(){D.show();A.hide();document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():c.normalScreen()});
E.click(function(){h.muted(!0);E.hide();B.show()});B.click(function(){h.muted(!1);E.show();B.hide()});w.mousedown(function(a){j=a.pageX-a.target.getBoundingClientRect().left;o=w.width();p.css("width",j);l.css("left",j-t/2);s=j/o;q(s)});l.mousedown(function(b){this.blur();u=!0;r=b.pageX;j=p.width();o=w.width();g.bind("mousemove",k);a(document).bind("mouseup",d)});l.bind("touchstart",function(a){e=a.originalEvent;l.blur();a=e.targetTouches[0];u=!0;r=a.pageX;j=p.width();o=w.width();l.bind("touchmove",
m);l.bind("touchend",i)});this.setPlayer=function(a){h=a};this.started=function(){y.hide();v.show();C.hide()};this.paused=function(){y.show();v.hide();C.show()};this.stopped=function(){y.show();v.hide();C.show()};this.setDuration=function(a){n=a};this.timeUpdate=function(){if(h.playTime()&&(H=SewisePlayerSkin.Utils.stringer.dateToStrHMS(new Date(1E3*Math.ceil(h.playTime().getTime()/1E3/n)*n)),G=SewisePlayerSkin.Utils.stringer.dateToStrHMS(new Date(1E3*Math.floor(h.playTime().getTime()/1E3/n)*n)),
J.text(G+"/"+H),!u)){j=100*(Math.floor(h.playTime().getTime()/1E3)%n/n)+"%";p.css("width",j);var a=p.width()-t/2;l.css("left",a);a=Math.ceil(h.playTime().getTime()/1E3/3600);a=100*(Math.floor(h.liveTime().getTime()/1E3/3600)>=a?1:Math.floor(h.liveTime().getTime()/1E3)%n/n)+"%";K.css("width",a)}};this.hide2=function(){x.hide()}}})(window.jQuery);(function(a,b){b(document).ready(function(){var a=SewisePlayer.ILivePlayer,b=new SewisePlayerSkin.ElementObject,k=new SewisePlayerSkin.ElementLayout(b),d=new SewisePlayerSkin.LogoBox(b),m=new SewisePlayerSkin.TopBar(b),i=new SewisePlayerSkin.ControlBar(b,k,m);SewisePlayerSkin.ILiveSkin.player=function(b){a=b;i.setPlayer(a)};SewisePlayerSkin.ILiveSkin.started=function(){i.started()};SewisePlayerSkin.ILiveSkin.paused=function(){i.paused()};SewisePlayerSkin.ILiveSkin.stopped=function(){i.stopped()};
SewisePlayerSkin.ILiveSkin.duration=function(a){i.setDuration(a)};SewisePlayerSkin.ILiveSkin.timeUpdate=function(){i.timeUpdate();m.setClock(a.playTime())};SewisePlayerSkin.ILiveSkin.programTitle=function(a){m.setTitle(a)};SewisePlayerSkin.ILiveSkin.logo=function(a){d.setLogo(a)};SewisePlayerSkin.ILiveSkin.volume=function(){};SewisePlayerSkin.ILiveSkin.clarityButton=function(){};SewisePlayerSkin.ILiveSkin.timeDisplay=function(){};SewisePlayerSkin.ILiveSkin.controlBarDisplay=function(a){"enable"!=
a&&i.hide2()};SewisePlayerSkin.ILiveSkin.topBarDisplay=function(a){"enable"!=a&&m.hide2()};SewisePlayerSkin.ILiveSkin.customStrings=function(){};try{SewisePlayer.CommandDispatcher.dispatchEvent({type:SewisePlayer.Events.PLAYER_SKIN_LOADED,playerSkin:SewisePlayerSkin.ILiveSkin})}catch(q){console.log("No Main Player")}})})(window,window.jQuery);
