/*
 * Name: VodWhite SewisePlayerSkin framework V1.0.0
 * Author: Jack Zhang
 * Website: http://www.sewise.com/
 * Date: 24th March 2014
 * Copyright: 2014, Sewise
 * 
 */

(function(b){b.SewisePlayerSkin={version:"1.0.0"};b.SewisePlayer=b.SewisePlayer||{}})(window);(function(b){b.SewisePlayer.IVodPlayer=b.SewisePlayer.IVodPlayer||{play:function(){},pause:function(){},stop:function(){},seek:function(){},changeClarity:function(){},setVolume:function(){},toPlay:function(){},duration:function(){},playTime:function(){},type:function(){},showTextTip:function(){},hideTextTip:function(){},muted:function(){}}})(window);(function(b){b.SewisePlayerSkin.IVodSkin=b.SewisePlayerSkin.IVodSkin||{player:function(){},started:function(){},paused:function(){},stopped:function(){},seeking:function(){},buffering:function(){},bufferProgress:function(){},loadedProgress:function(){},programTitle:function(){},duration:function(){},playTime:function(){},startTime:function(){},loadSpeed:function(){},initialClarity:function(){},lang:function(){},logo:function(){},timeUpdate:function(){},volume:function(){},clarityButton:function(){},
timeDisplay:function(){},controlBarDisplay:function(){},topBarDisplay:function(){},customStrings:function(){}}})(window);(function(){SewisePlayerSkin.Utils={stringer:{time2FigFill:function(b){var a,b=Math.floor(b);10>b?a="0"+b:a=""+b;return a},secondsToHMS:function(b){if(!(0>b)){var a=this.time2FigFill(Math.floor(b/3600)),d=this.time2FigFill(b/60%60),b=this.time2FigFill(b%60);return a+":"+d+":"+b}},secondsToMS:function(b){if(!(0>b)){var a=this.time2FigFill(b/60),b=this.time2FigFill(b%60);return a+":"+b}},dateToTimeString:function(b){var a;a=b?b:new Date;var b=a.getFullYear(),d=a.getMonth()+1,c=a.getDate(),j=this.time2FigFill(a.getHours()),
f=this.time2FigFill(a.getMinutes());a=this.time2FigFill(a.getSeconds());return b+"-"+d+"-"+c+" "+j+":"+f+":"+a},dateToTimeStr14:function(b){var a=b.getFullYear(),d=this.time2FigFill(b.getMonth()+1),c=this.time2FigFill(b.getDate()),j=this.time2FigFill(b.getHours()),f=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+d+c+j+f+b},dateToStrHMS:function(b){var a=this.time2FigFill(b.getHours()),d=this.time2FigFill(b.getMinutes()),b=this.time2FigFill(b.getSeconds());return a+
":"+d+":"+b}}}})();(function(b){SewisePlayerSkin.ElementObject=function(){this.$sewisePlayerUi=b(".sewise-player-ui");this.$container=this.$sewisePlayerUi.parent();this.$video=this.$container.find("video").get(0);this.$controlbar=this.$sewisePlayerUi.find(".controlbar");this.$playBtn=this.$sewisePlayerUi.find(".controlbar-btns-play");this.$pauseBtn=this.$sewisePlayerUi.find(".controlbar-btns-pause");this.$stopBtn=this.$sewisePlayerUi.find(".controlbar-btns-stop");this.$fullscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-fullscreen");
this.$normalscreenBtn=this.$sewisePlayerUi.find(".controlbar-btns-normalscreen");this.$soundopenBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundopen");this.$soundcloseBtn=this.$sewisePlayerUi.find(".controlbar-btns-soundclose");this.$playtime=this.$sewisePlayerUi.find(".controlbar-playtime");this.$controlBarProgress=this.$sewisePlayerUi.find(".controlbar-progress");this.$progressPlayedLine=this.$sewisePlayerUi.find(".controlbar-progress-playedline");this.$progressPlayedPoint=this.$sewisePlayerUi.find(".controlbar-progress-playpoint");
this.$progressLoadedLine=this.$sewisePlayerUi.find(".controlbar-progress-loadedline");this.$progressSeekLine=this.$sewisePlayerUi.find(".controlbar-progress-seekline");this.$logo=this.$sewisePlayerUi.find(".logo");this.$logoIcon=this.$sewisePlayerUi.find(".logo-icon");this.$topbar=this.$sewisePlayerUi.find(".topbar");this.$programTitle=this.$sewisePlayerUi.find(".topbar-program-title");this.$topbarClock=this.$sewisePlayerUi.find(".topbar-clock");this.$buffer=this.$sewisePlayerUi.find(".buffer");this.$bigPlayBtn=
this.$sewisePlayerUi.find(".big-play-btn");this.defStageWidth=this.$container.width();this.defStageHeight=this.$container.height();this.defLeftValue=parseInt(this.$container.css("left"));this.defTopValue=parseInt(this.$container.css("top"));this.defOffsetX=this.$container.get(0).getBoundingClientRect().left;this.defOffsetY=this.$container.get(0).getBoundingClientRect().top;this.defOverflow=b("body").css("overflow")}})(window.jQuery);(function(b){SewisePlayerSkin.ElementLayout=function(a){function d(){null!=document.fullscreenElement||null!=document.msFullscreenElement||null!=document.mozFullScreenElement||null!=document.webkitFullscreenElement?m.fullScreen():m.normalScreen()}var c=a.$container,j=a.$controlBarProgress,f=a.$playtime,m=this,g=a.defStageWidth,p=a.defStageHeight,s=a.defLeftValue,q=a.defTopValue,t=a.defOffsetX,r=a.defOffsetY,E=a.defOverflow,h=parseInt(g)-288;0>h&&(h+=f.width(),f.hide());j.css("width",h);document.addEventListener("fullscreenchange",
d);document.addEventListener("MSFullscreenChange",d);document.addEventListener("mozfullscreenchange",d);document.addEventListener("webkitfullscreenchange",d);this.fullScreen=function(a){if("not-support"==a){var a=b(window).width(),d=b(window).height()-8;c.css("width",a);c.css("height",d);a=q-r+"px";c.css("left",s-t+"px");c.css("top",a);b("body").css("overflow","hidden")}else c.css("width","100%"),c.css("height","100%");a=parseInt(c.width())-288;0>a?(a+=f.width(),f.hide()):f.show();j.css("width",a)};
this.normalScreen=function(){c.css("width",g);c.css("height",p);c.css("left",s);c.css("top",q);b("body").css("overflow",E);h=parseInt(g)-288;0>h?(h+=f.width(),f.hide()):f.show();j.css("width",h)}}})(window.jQuery);(function(){SewisePlayerSkin.LogoBox=function(b){var a=b.$logoIcon;this.setLogo=function(b){a.css("background","url("+b+") 0px 0px no-repeat");a.attr("href","http://www.sewise.com/")}}})(window.jQuery);(function(){SewisePlayerSkin.TopBar=function(b){var a=b.$topbar,d=b.$programTitle,c=b.$topbarClock;setInterval(function(){var a=SewisePlayerSkin.Utils.stringer.dateToTimeString();c.text(a)},1E3);this.setTitle=function(a){d.text(a)};this.show=function(){a.css("visibility","visible")};this.hide=function(){a.css("visibility","hidden")};this.hide2=function(){a.hide()}}})(window.jQuery);(function(b){SewisePlayerSkin.ControlBar=function(a,d,c){function j(a){a=i+(a.pageX-u);0<a&&a<n&&(o.css("width",a),k.css("left",a-y/2))}function f(a){p.unbind("mousemove",j);b(document).unbind("mouseup",f);B=a.pageX;u!=B&&(i=o.width(),v=i/n,l.seek(v*w));z=!1}function m(a){e=a.originalEvent;1==e.targetTouches.length&&(e.preventDefault(),a=i+(e.targetTouches[0].pageX-u),0<a&&a<n&&(o.css("width",a),k.css("left",a-y/2)))}function g(a){e=a.originalEvent;k.unbind("touchmove",m);k.unbind("touchend",g);if(1==
e.changedTouches.length)B=e.changedTouches[0].pageX,u!=B&&(i=o.width(),v=i/n,l.seek(v*w));z=!1}var p=a.$container,s=a.$video,q=a.$controlbar,t=a.$playBtn,r=a.$pauseBtn,E=a.$stopBtn,h=a.$fullscreenBtn,x=a.$normalscreenBtn,F=a.$soundopenBtn,C=a.$soundcloseBtn,K=a.$playtime,o=a.$progressPlayedLine,k=a.$progressPlayedPoint,L=a.$progressLoadedLine,A=a.$progressSeekLine,M=a.$buffer,D=a.$bigPlayBtn,l,w=0.1,G=0,I="00:00:00",J="00:00:00",y=0,z=!1,u=0,B=0,i=0,n=0,v=0,H=!0,y=k.width(),n=A.width();r.hide();x.hide();
C.hide();M.hide();q.click(function(a){a.originalEvent.stopPropagation()});p.click(function(){H?(q.css("visibility","hidden"),c.hide(),H=!1):(q.css("visibility","visible"),c.show(),H=!0)});t.click(function(){l.play()});r.click(function(){l.pause()});E.click(function(){l.stop()});D.click(function(a){a.originalEvent.stopPropagation();l.play()});h.click(function(){h.hide();x.show();var a=p.get(0);a.requestFullscreen?a.requestFullscreen():a.msRequestFullscreen?a.msRequestFullscreen():a.mozRequestFullScreen?
a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():s.webkitEnterFullscreen?(s.play(),s.webkitEnterFullscreen(),h.show(),x.hide()):d.fullScreen("not-support")});x.click(function(){h.show();x.hide();document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():d.normalScreen()});F.click(function(){l.muted(!0);
F.hide();C.show()});C.click(function(){l.muted(!1);F.show();C.hide()});A.mousedown(function(a){i=a.pageX-a.target.getBoundingClientRect().left;n=A.width();o.css("width",i);k.css("left",i-y/2);v=i/n;l.seek(v*w)});k.mousedown(function(a){this.blur();z=!0;u=a.pageX;i=o.width();n=A.width();p.bind("mousemove",j);b(document).bind("mouseup",f)});k.bind("touchstart",function(a){e=a.originalEvent;k.blur();a=e.targetTouches[0];z=!0;u=a.pageX;i=o.width();n=A.width();k.bind("touchmove",m);k.bind("touchend",g)});
this.setPlayer=function(a){l=a};this.started=function(){t.hide();r.show();D.hide()};this.paused=function(){t.show();r.hide();D.show()};this.stopped=function(){t.show();r.hide();D.show()};this.setDuration=function(a){w=a;J=SewisePlayerSkin.Utils.stringer.secondsToHMS(w)};this.timeUpdate=function(a){G=a;I=SewisePlayerSkin.Utils.stringer.secondsToHMS(G);K.text(I+"/"+J);z||(i=100*(G/w)+"%",o.css("width",i),a=o.width()-y/2,k.css("left",a))};this.loadProgress=function(a){L.css("width",100*a+"%")};this.hide2=
function(){q.hide()}}})(window.jQuery);(function(b,a){a(document).ready(function(){var a=SewisePlayer.IVodPlayer,b=new SewisePlayerSkin.ElementObject,j=new SewisePlayerSkin.ElementLayout(b),f=new SewisePlayerSkin.LogoBox(b),m=new SewisePlayerSkin.TopBar(b),g=new SewisePlayerSkin.ControlBar(b,j,m);SewisePlayerSkin.IVodSkin.player=function(b){a=b;g.setPlayer(a)};SewisePlayerSkin.IVodSkin.started=function(){g.started()};SewisePlayerSkin.IVodSkin.paused=function(){g.paused()};SewisePlayerSkin.IVodSkin.stopped=function(){g.stopped()};SewisePlayerSkin.IVodSkin.duration=
function(a){g.setDuration(a)};SewisePlayerSkin.IVodSkin.timeUpdate=function(a){g.timeUpdate(a)};SewisePlayerSkin.IVodSkin.loadedProgress=function(a){g.loadProgress(a)};SewisePlayerSkin.IVodSkin.programTitle=function(a){m.setTitle(a)};SewisePlayerSkin.IVodSkin.logo=function(a){f.setLogo(a)};SewisePlayerSkin.IVodSkin.volume=function(){};SewisePlayerSkin.IVodSkin.initialClarity=function(){};SewisePlayerSkin.IVodSkin.clarityButton=function(){};SewisePlayerSkin.IVodSkin.timeDisplay=function(){};SewisePlayerSkin.IVodSkin.controlBarDisplay=
function(a){"enable"!=a&&g.hide2()};SewisePlayerSkin.IVodSkin.topBarDisplay=function(a){"enable"!=a&&m.hide2()};SewisePlayerSkin.IVodSkin.customStrings=function(){};try{SewisePlayer.CommandDispatcher.dispatchEvent({type:SewisePlayer.Events.PLAYER_SKIN_LOADED,playerSkin:SewisePlayerSkin.IVodSkin})}catch(p){console.log("No Main Player")}})})(window,window.jQuery);
